### ISSUE TITLE
Better handling for much wanted pickups

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#1242]
I opened a thread on the community forum about this: https://community.foodsaving.world/t/how-to-handle-much-wanted-pickups/214
Now awaiting feedback and see if it makes sense to propose a feature.

**Comment by tiltec** [comment]
Based on the [discussion](https://community.foodsaving.world/t/how-to-handle-much-wanted-pickups/214) I can see it's a hot topic in groups. I re-read the thread and those solutions were proposed:
- have store managers to confirm pickup joins ([source](https://community.foodsaving.world/t/how-to-handle-much-wanted-pickups/214/6?u=tiltec))
- add recent pickup history to pickup join dialog ([source](https://community.foodsaving.world/t/how-to-handle-much-wanted-pickups/214/8?u=tiltec))
- restrict how often people can sign up per week / per x weeks
- implement a currency: spend "money" for wanted pickups, get "money" for unwanted pickups ([source](https://community.foodsaving.world/t/how-to-handle-much-wanted-pickups/214/16?u=tiltec))
- show historic pickups in pickup list ([source](https://community.foodsaving.world/t/how-to-handle-much-wanted-pickups/214/25?u=tiltec))

I haven't made up my mind yet what I would like to implement. Just some thoughts for now.
The topic seems to be about fairness, but it's unclear how fairness can be achieved. Should those who can pick up more unwanted stuff also get more nice stuff? Should there be equal chances to get the nice stuff? I think it would be nice if those who need something distribute the available resources amongst them, but the fear of "not getting enough" might get in the way of achieving a fair outcome. 
- More transparency ("show historic pickups") might make the problem worse: people would readily see the unequal distribution, but they don't see why it could be justified. 
- Adding rules might create a feeling of fairness, but ignoring the differences in peoples needs. 
  - a currency seems like rules to me, more flexible but also quite complex  
- Having store managers would delegate the power of distributing the resources to a few people, so it probably needs checks & balances.

**Comment by tiltec** [comment]
#1520 might also help a bit here.

**Comment by nicksellen** [comment]
Just re-opening and marking as _important_, as the forum discussion has a lot of interesting, and some quite implementable ideas, and it's a topic that touches a lot of groups.

**Comment by nicksellen** [comment]
Our current governance design process looks like it'll address some of these topics, if, when we come to a more concrete implementation, then we should revisit this to make sure we address the points.

**Comment by dwaxweiler** [comment]
I want to add the idea of a raffle for much wanted activities: You can sign up until one week in advance, and the system randomly selects the people that should go. Such a feature could be enabled per series of activities and per activity to be only used when needed. It should only be possible for pickups planned longer in advance as I fear that it could become messy and stressful if the draw happens too short in advance. If somebody steps back after the draw, the system could randomly select a new person from the initially signed up people; If none is left, the slot opens for everybody not being part in the raffle.

Such a draw could also be fed by historical data so that new people or people that have been left out in the past get a higher chance, but I think this balancing needs much more thought and quickly becomes complex.

**Comment by nicksellen** [comment]
Moved to codeberg https://codeberg.org/karrot/karrot-frontend/issues/1242

Still the eternally important issue though!
