### ISSUE TITLE
Filter activities by day of the week

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2310]
I forward the idea of one friend at Foodsharing Luxembourg: It would be nice to have a filter by day of the week (Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday) to the activities page as they can only be active on a few days of the week.

**Comment by brnsolikyl** [comment]
What about a calendar view of the activities? It can give a nice overview of the day, week or even month.

**Comment by dwaxweiler** [comment]
@brnsolikyl Sure, a week view would also fulfil the same need I guess. It would only require more work.

**Comment by esharb** [comment]
Hi, I'm a first-time contributor and would love to work on this issue! Do let me know if it's possible. Thank you!

**Comment by brnsolikyl** [comment]
> Hi, I'm a first-time contributor and would love to work on this issue! Do let me know if it's possible. Thank you!

Hi @esharb You're welcome to contribute! I answered you on chat.foodsaving.world with more info but usually it does not send out e-mail notifications.

**Comment by esharb** [comment]
> > Hi, I'm a first-time contributor and would love to work on this issue! Do let me know if it's possible. Thank you!
> 
> Hi @esharb You're welcome to contribute! I answered you on chat.foodsaving.world with more info but usually it does not send out e-mail notifications.

Thank you!

**Comment by dwaxweiler** [comment]
This would still help people only available on a specific day of the week.

**Comment by danclee336** [comment]
Hi, I'm interested in working on this. Can I get assigned to this?

**Comment by nicksellen** [comment]
@danclee336 sure! what do you need to know to get started?

**Comment by danclee336** [comment]
I'm trying to access the activities page mentioned in this issue but could not find it. Also, this is my first time working on an open-source project, any advice on how to start?

**Comment by dwaxweiler** [comment]
This would still be useful.

**Comment by kkreine** [comment]
@nicksellen Is this still a requested feature you think should be added? If so, I'd be happy to work on this.

I see from #2460 that a select would be best to match the other filters on the page. Do you think this should allow multi-select? I think that PR gives me plenty of info to start with. If it's fine for me to proceed, I can let you know if I end up with further questions.

**Comment by nicksellen** [comment]
Hey @kkreine, yes, indeed it is still a requested feature, @dwaxweiler actually just re-requested it a couple of days ago.

There is a topic over on our forum for it where we're started to keep user-level issues/tasks --> https://community.karrot.world/t/filter-activities-by-day-of-the-week/1393 (and leaving github for more technical stuff).

> I see from https://github.com/karrot-dev/karrot-frontend/pull/2460 that a select would be best to match the other filters on the page. Do you think this should allow multi-select?

Great that you found that previous attempt, and I think, yes, a multi select would be great.

One thing that might have changed since that attempt was that the filters are applied on the backend/server now, so this issue will also require backend work, is that something you're comfortable with, otherwise perhaps we can find another collaborator willing to do that (or me if not). What do you think?
