### ISSUE TITLE
activity.feedbackDismissedBy is a list of users, could be a boolean?

### ISSUE THREAD

**Issue by tiltec** [karrot-dev/karrot-frontend#2381]
I noticed that activity.feedbackDismissedBy is a list of users that already dismissed the feedback for this activity, but the frontend only needs to know if the current user dismissed the feedback (to determine if the prompt should be shown or not).

backend:
https://github.com/yunity/karrot-backend/blob/0fd4f36e6e7964877f1afab2070ab0387b33466c/karrot/activities/serializers.py#L195-L197

frontend:
https://github.com/yunity/karrot-frontend/blob/8c3122a93f330ecae426c9657ca5006ea81a0cd3/src/activities/datastore/activities.js#L66

As far as I'm concerned, it would be cleaner to make this into a boolean (e.g. `isFeedbackDismissed`) - less information transferred, less enriching/filtering work in frontend.

Is there any reason to keep the current behavior?

**Comment by larzon83** [comment]
@tiltec this was a PR from the Freiburg group. I think we did it this way because we copy/pasted. I don't  remember exactly.
I totally see your point.
I have no clue about the backend. Maybe @pogopaule?
For the frontend, this would mean we could ditch the enrichment of `feedbackDismissedBy ` and the filter then would be like this?
```js
.filter(p => !p.isFeedbackDismissed) 
```
