### ISSUE TITLE
Add number of places to statistics page

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2515]
I suggest to add to the statistics page some details about the groups' places:
- the number of places per status
- places filterable by year

Two use cases from my group:
- We regularly publish how many places we are cooperating with. At the moment, we count them manually.
- We sometimes need the number of new places of a specific time period, usually one year, for end of year reviews or funding reports.

**Comment by yatharthchhabra** [comment]
Hi, I'm enrolled in a Software Engineering course at the University of Michigan. My partner and I would like to take charge of this issue and resolve it as part of our class project. 

We are a bit confused about the exact issue since it seems those features are already implemented. As you can see on the first screenshot, there is a total for number of places per status on the bottom row. Also, the second screenshot shows that you can filter by year. Please let me know if we have misunderstood. Thanks!

<img width="822" alt="Screen Shot 2022-04-12 at 8 52 57 PM" src="https://user-images.githubusercontent.com/59714564/163077780-1b056247-5024-42b0-8846-9fab665e8818.png">

<img width="207" alt="Screen Shot 2022-04-12 at 8 54 23 PM" src="https://user-images.githubusercontent.com/59714564/163077891-a3e118b6-68b0-4b11-ae70-aa6f00c3a51d.png">

**Comment by dwaxweiler** [comment]
Welcome @yatharthchhabra, I am happy to read that both of you are considering contributing to Karrot!

With "status" I meant the one of the place with the values "co-operating", "negotiating" and so on; You can change this on the place's edit page.

I think it would already be enough to add the total number of places to the table of your first screenshot, specifically to the cell in the last row and first column, which is currently empty. Just having this number would already satisfy my use cases; We can leave out the status for sure.

**Comment by dwaxweiler** [comment]
Hi @yatharthchhabra, are you still interested in this issue?

**Comment by yatharthchhabra** [comment]
Unfortunately, we will not be able to help with this issue. Sorry about
that!
