### ISSUE TITLE
Add group settings to limit number of slots you can sign up for

### ISSUE THREAD

**Issue by dwaxweiler** [karrot-dev/karrot-frontend#2636]
In my group, we have introduced a rule to limit the number of slots you can sign up for to 1 per cooperation per week and to 3 in general per week. If the slot is still available 24 hours in advance, you can sign up for it no matter what.

It should be possible to configure such rules as group level settings.

**Comment by dwaxweiler** [comment]
also mentioned in https://github.com/karrot-dev/karrot-frontend/issues/1242#issuecomment-487301885

**Comment by nathalie-sz** [comment]
Interesting that this is coming up in your group, foodsharing.de has a new feature like that since the last release see https://gitlab.com/foodsharing-dev/foodsharing/-/merge_requests/2414
Although I find that implementation a bit confusing. 

To me it sounds that 'once per week' is rather a place setting, whereas '3 times overall per week across places' is a group setting? I wonder if the place setting would be enough to start with. Maybe adding it to the 'place types' settings? 

Also if you have activities for meetings, events or such, you probably don't want to count those.

**Comment by nathalie-sz** [comment]
But I don't know how likely it is that there is someone following up on this soon... maybe keep it in mind for our potential in person meeting? :)

**Comment by brnsolikyl** [comment]
Oh that's been kind of an old discussion. Still relevant though! Here's a thread for reference: https://community.karrot.world/t/how-to-handle-much-wanted-pickups/214
