### ISSUE TITLE
Copy recommendation on Create New Group page 

### ISSUE THREAD

**Issue by sbutler-gh** [karrot-dev/karrot-frontend#2706]
On the [Create New Group page](https://karrot.world/#/group/create), I was confused by the **public group information** and **group description** textareas — I thought they was asking me for the same information, I wasn't sure what the difference was.  Only when I investigated closer did I realize the difference.  I thought some small copy changes could make this easier to understand off the bat, like this:

`Public group information (visible to everyone)`

`Internal group description (visible to members)`

Here is what the page currently looks like
<img width="868" alt="Screen Shot 2024-02-19 at 9 06 53 PM" src="https://github.com/karrot-dev/karrot-frontend/assets/46165064/8ffb374e-889a-433d-a6a1-6a66c5851309">

And what it could look like with this kind of change:
<img width="856" alt="Screen Shot 2024-02-19 at 9 07 48 PM" src="https://github.com/karrot-dev/karrot-frontend/assets/46165064/8f890508-6f7c-41e7-b337-393eff2abe11">

**Comment by nicksellen** [comment]
Yup, makes sense! Are you interested to contribute the change? (not sure if you have that interest/skills).

Although, it might be worth changing the second one to "Internal group _information_", as in practise that's how it's often used.

We have this input too: https://community.karrot.world/t/transform-private-group-description-into-group-wall-description/1505 which explains the use case more like group _information_:

> A description above the main wall would be really useful to show some common group stuff (reminder of rules, links to important documents or websites…).

There was also a previous pull request to rename the actual field to group information too (https://github.com/karrot-dev/karrot-frontend/pull/2465 and https://github.com/karrot-dev/karrot-backend/pull/1211), but unfortunately was not completed/merged (oops looks like my fault 🤦).

I'll cross reference this thread with our community forum one, and see what input is there! Getting the wording right is really important as can really confuse people otherwise (like you experienced).

**Comment by nicksellen** [comment]
So, from the input on the community forum, I think we could go with:
- Public group information (visible to everyone)
- Internal group description (visible to members only) 

I'd suggest we have the parenthesis bits as seperate i18n strings, so they could be used elsewhere..., so 4 string in total:
- Public group information
- Internal group description
- visible to everyone
- visible to members only

**Comment by nicksellen** [comment]
As in other PR thread, we moved to codeberg!

See https://codeberg.org/karrot/karrot-frontend/issues/2706
